services:
  web:
    build:
      dockerfile: Dockerfile.prod
    command: gunicorn --timeout 120 config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .env.prod
    expose:
      - 8000
  nginx:
    image: nginx:latest
    # ports:
    #   - "80:80"
    volumes:
      - ./nginx/conf.d/app.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/static
      - media_volume:/app/media

    depends_on:
      - web
volumes:
  static_volume:
  media_volume:
